updated setup

diff --git a/laravel/setup b/laravel/setup
--- a/laravel/setup
+++ b/laravel/setup
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # check for required packages
-for pkg in composer php php-cli php-xml mysql-server mysql-client
+for pkg in composer php php-cli php-xml php-curl mysql-server mysql-client
 do
     if ! dpkg -s $pkg | grep -q "Status: install ok installed"
     then
@@ -12,6 +12,7 @@ done
 # install missing packages
 if [ ${#PKG[@]} -gt 0 ]
 then
+    echo "installing package(s) "${PKG[@]}" (may ask sudo password)..."
     if ! sudo apt install -y "${PKG[@]}"
     then
 	echo "some required ubuntu packages (${PKG[@]}) failed to install"
@@ -22,7 +23,12 @@ fi
 # create quickstart
 if [ ! -d quickstart ]
 then
-   composer create-project laravel/laravel quickstart --prefer-dist
+    echo "creating quickstart project..."
+    if ! composer create-project laravel/laravel quickstart --prefer-dist
+    then
+	echo "composer failed."
+	exit 1
+    fi
 fi
 
 # bash function to create random 256 bit key as 64 characters that
@@ -40,11 +46,12 @@ cd quickstart
 # setup database if it has not been setup before
 if egrep -q "^DB_PASSWORD=$" .env
 then
-   DB_NAME=laravel-quickstart-db
-   DB_USER=laravel-quickstart-user
-   DB_PASS="$(key256)"
-   sudo mysql <<SQL
-CREATE DATABASE IF NOT EXISTS \`$DB_NAME\`;
+    echo "creating quickstart mysql database and editing quickstart/.env (may require sudo password)..."
+    DB_NAME=laravel-quickstart-db
+    DB_USER=laravel-quickstart-user
+    DB_PASS="$(key256)"
+    sudo mysql <<SQL
+CREATE 	 DATABASE IF NOT EXISTS \`$DB_NAME\`;
 DROP USER IF EXISTS '$DB_USER'@'localhost';
 CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';
 GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER
@@ -56,3 +63,11 @@ SQL
          -e "s/^DB_USERNAME=.*$/DB_USERNAME='$DB_USER'/" \
          -e "s/^DB_PASSWORD=.*$/DB_PASSWORD='$DB_PASS'/" .env
 fi
+
+if ! php artisan migrate
+then
+    echo "artisan migrate failed."
+    exit 1
+fi
+
+echo "setup ok"
